version: '3.8'

services:
  backend:
    container_name: revvo_backend
    build: ./backend
    volumes: 
      - ./backend:/var/www/html/backend

  nginx:
    image: nginx:latest
    container_name: revvo_nginx
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/var/www/html/frontend
      - ./backend:/var/www/html/backend
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend