version: '3.8'

services:
  backend:
    container_name: revvo_backend
    build: ./backend
    volumes: 
      - ./backend:/var/www/html/backend
    depends_on:
      - database
    networks:
      - personal_network

  nginx:
    image: nginx:latest
    container_name: revvo_nginx
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/var/www/html/frontend
      - ./backend:/var/www/html/backend
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - personal_network

  database:
    image: mysql:8.0
    container_name: revvo_mysql
    environment:
      MYSQL_DATABASE: challenge_revvo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "2025:3306"
    volumes:
      - ./docker/db:/var/lib/mysql
    networks:
      - personal_network


networks:
  personal_network: